### PR TITLE
Fix handling of rate limit by checking response headers in transport

### LINKED ISSUE #11: Improve HTTPRateLimiter
The current [HTTPRateLimiter](https://github.com/src-d/ghsync/blob/master/utils/rate.go) it's not working properly since is hitting the rate and returning errors, instead of wait until the query can be done.

BTW The current implementation is copy pasted from terraform-github 
https://github.com/terraform-providers/terraform-provider-github/commit/263b46a926ca0f1c5b458ac547c04e12b3b43377

### PR DESCRIPTION
**Pull request by se7entyse7en**
Closes #11.

This fixes the rate limiter by checking the response headers and sleeping after the last remaining request has been done. See the issue for details.

### CODE REVIEW

File: utils/rate.go [hunk 1]
```diff
@@ -55,45 +52,37 @@ func (rlt *rateLimitTransport) RoundTrip(req *http.Request) (*http.Response, err
...
-	r1, r2, err := drainBody(resp.Body)
-	if err != nil {
-		return nil, err
-	}
-	resp.Body = r1
-	ghErr := github.CheckResponse(resp)
-	resp.Body = r2
-
-	// When you have been limited, use the Retry-After response header to slow down.
-	if arlErr, ok := ghErr.(*github.AbuseRateLimitError); ok {
```
Comment (smacker) [inline utils/rate.go]: do you think it makes sense to handle abuse as well? We don't need it right now because of the current logic in shallow command but we might hit it later. The check is simple: https://github.com/google/go-github/blob/master/github/github.go#L754

**Comment by carlosms** [comment]
Does it make sense to have tests for it? Or will it be completely mocked, and we won't be really testing much...?

File: utils/rate.go (hunk 1 above)
Comment (se7entyse7en) [reply utils/rate.go]: yup, I didn't add it because it wouldn't be useful the `shallow` command, but given its simplicity I guess that we can include it in this PR.

**Comment by se7entyse7en** [comment]
> Does it make sense to have tests for it? Or will it be completely mocked, and we won't be really testing much...?

I'd open an issue for this to decide also how to test, and this should also be part of the testing design doc. I guess that the main point is whether we want to mock or use a fake org. Even if we decide to mock, this feature would be tested anyway if we're able to assert that the sleep occurs.

File: utils/rate.go (hunk 1 above)
Comment (se7entyse7en) [reply utils/rate.go]: Reincluded abuse check [here](https://github.com/src-d/ghsync/pull/51/commits/5acc8d7146da5cd962bf5f1c53ba48aaae011790).
